<?php

return [
    'intro' => [
        'first' =>[
            'speaker_name' => 'Moi',
            'speaker_img' => 'me',
            'text' => 'With the emergence of digital technology and artificial intelligence, Fake News are becoming more prevalent and easily gaining momentum. They exist in every domain and affect all age groups. The goal of this serious game is to teach you, in a playful manner, how to spot them to better protect yourself.'
        ],
        'second' => [
            'speaker_name' => 'Moi',
            'speaker_img' => 'me',
            'text' => 'You will encounter three individuals, and you must assist them in determining whether what they see, read, or hear is true or if it has been invented and generated by artificial intelligence. You can ask for clues, but it will deduct points! <br> Together, let\'s restore the truth!'
        ],
    ]
];
